maven.samples/samples_src/javaee7/jsf/fileUpload/src/main/java/fileupload/FileUploadBean.java
/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright (c) 1997-2013 Oracle and/or its affiliates. All rights reserved.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common Development
 * and Distribution License("CDDL") (collectively, the "License").  You
 * may not use this file except in compliance with the License.  You can
 * obtain a copy of the License at
 * https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html
 * or packager/legal/LICENSE.txt.  See the License for the specific
 * language governing permissions and limitations under the License.
 *
 * When distributing the software, include this License Header Notice in each
 * file and include the License file at packager/legal/LICENSE.txt.
 *
 * GPL Classpath Exception:
 * Oracle designates this particular file as subject to the "Classpath"
 * exception as provided by Oracle in the GPL Version 2 section of the License
 * file that accompanied this code.
 *
 * Modifications:
 * If applicable, add the following below the License Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * "Portions Copyright [year] [name of copyright owner]"
 *
 * Contributor(s):
 * If you wish your version of this file to be governed by only the CDDL or
 * only the GPL Version 2, indicate your decision by adding "[Contributor]
 * elects to include this software in this distribution under the [CDDL or GPL
 * Version 2] license."  If you don't indicate a single choice of license, a
 * recipient has the option to distribute your version of this file under
 * either the CDDL, the GPL Version 2 or to extend the choice of license to
 * its licensees as provided above.  However, if you add GPL Version 2 code
 * and therefore, elected the GPL Version 2 license, then the option applies
 * only if the new code is made subject to such option by the copyright
 * holder.
 */

package fileUpload;

import java.io.IOException;
import java.io.InputStream;
import java.util.Scanner;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;
import javax.servlet.http.Part;

@Named
@RequestScoped
public class FileUploadBean {

    public FileUploadBean() {
    }
    private Part uploadedFile;

    public Part getUploadedFile() {
        return uploadedFile;
    }

    public void setUploadedFile(Part uploadedFile) {
        this.uploadedFile = uploadedFile;
    }
    
    public String getFileText() {
        String text = "";

        if (null != uploadedFile) {
            try {
                InputStream is = uploadedFile.getInputStream();
                text = new Scanner( is ).useDelimiter("\\A").next();
            } catch (IOException ex) {
                
            }
        }
        return text;
    }
    
}

maven.samples/samples_src/javaee7/jsf/fileUpload/src/main/webapp/index.xhtml
<!--

    DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.

    Copyright (c) 1997-2013 Oracle and/or its affiliates. All rights reserved.

    The contents of this file are subject to the terms of either the GNU
    General Public License Version 2 only ("GPL") or the Common Development
    and Distribution License("CDDL") (collectively, the "License").  You
    may not use this file except in compliance with the License.  You can
    obtain a copy of the License at
    https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html
    or packager/legal/LICENSE.txt.  See the License for the specific
    language governing permissions and limitations under the License.

    When distributing the software, include this License Header Notice in each
    file and include the License file at packager/legal/LICENSE.txt.

    GPL Classpath Exception:
    Oracle designates this particular file as subject to the "Classpath"
    exception as provided by Oracle in the GPL Version 2 section of the License
    file that accompanied this code.

    Modifications:
    If applicable, add the following below the License Header, with the fields
    enclosed by brackets [] replaced by your own identifying information:
    "Portions Copyright [year] [name of copyright owner]"

    Contributor(s):
    If you wish your version of this file to be governed by only the CDDL or
    only the GPL Version 2, indicate your decision by adding "[Contributor]
    elects to include this software in this distribution under the [CDDL or GPL
    Version 2] license."  If you don't indicate a single choice of license, a
    recipient has the option to distribute your version of this file under
    either the CDDL, the GPL Version 2 or to extend the choice of license to
    its licensees as provided above.  However, if you add GPL Version 2 code
    and therefore, elected the GPL Version 2 license, then the option applies
    only if the new code is made subject to such option by the copyright
    holder.

-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:jsf="http://xmlns.jcp.org/jsf">

<section>
   <h1>JSF 2.2 File Upload Samples</h1>
   <article>
      <p>This sample demonstrates the use of a simple file upload component introduced in JSF 2.2.<br/>
         One option demonstrates a traditional file upload operation, while the other option<br/>
         demonstrates a file upload operation over Ajax.<br/>
         For both options, Click on the "Browse" button and navigate to the<br/>
         <i>javaee7/jsf/fileupload</i> directory.  choose one of <i>inputFileFailure.txt</i> or <br/>
         <i>inputFileSuccess.txt .</i>  Then press the <i>Upload</i> button.  There is a validator
         attached to the file input component that examines the contents of the uploaded file, <br/>
         looking for the string <i>JSR-344</i>.  The <i>inputFileFailure.txt</i> file does not contain<br/>
         the string so you should see a validation error.  The <i>inputFileSuccess.txt</i> file<br/>
         contains the JSR-344 string so you should see a success message.</p> 
   </article>
</section>

<form jsf:id="form">
   <h:commandButton value="Continue to Sample" action="inputFile"/>
   <br/>
   <br/>
   <h:commandButton value="Continue to Ajax Sample" action="inputFileAjax"/>

</form>

</html>

maven.samples/samples_src/javaee7/jsf/fileUpload/src/main/webapp/inputFile.xhtml
<!--

    DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.

    Copyright (c) 1997-2013 Oracle and/or its affiliates. All rights reserved.

    The contents of this file are subject to the terms of either the GNU
    General Public License Version 2 only ("GPL") or the Common Development
    and Distribution License("CDDL") (collectively, the "License").  You
    may not use this file except in compliance with the License.  You can
    obtain a copy of the License at
    https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html
    or packager/legal/LICENSE.txt.  See the License for the specific
    language governing permissions and limitations under the License.

    When distributing the software, include this License Header Notice in each
    file and include the License file at packager/legal/LICENSE.txt.

    GPL Classpath Exception:
    Oracle designates this particular file as subject to the "Classpath"
    exception as provided by Oracle in the GPL Version 2 section of the License
    file that accompanied this code.

    Modifications:
    If applicable, add the following below the License Header, with the fields
    enclosed by brackets [] replaced by your own identifying information:
    "Portions Copyright [year] [name of copyright owner]"

    Contributor(s):
    If you wish your version of this file to be governed by only the CDDL or
    only the GPL Version 2, indicate your decision by adding "[Contributor]
    elects to include this software in this distribution under the [CDDL or GPL
    Version 2] license."  If you don't indicate a single choice of license, a
    recipient has the option to distribute your version of this file under
    either the CDDL, the GPL Version 2 or to extend the choice of license to
    its licensees as provided above.  However, if you add GPL Version 2 code
    and therefore, elected the GPL Version 2 license, then the option applies
    only if the new code is made subject to such option by the copyright
    holder.

-->
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:form id="form" enctype="multipart/form-data" prependId="false">
        
        <p><h:inputFile id="file" value="#{fileUploadBean.uploadedFile}"> 
           <f:validator validatorId="FileValidator" />
       </h:inputFile>
        </p>
       <br/>
       
       <h:commandButton id="button" value="Upload"/>
       
       #{fileUploadBean.fileText}
       
       <p><h:messages id="messages" /></p>
    </h:form>

</html>

maven.samples/samples_src/javaee7/jsf/fileUpload/src/main/webapp/inputFileAjax.xhtml
<!--

    DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.

    Copyright (c) 1997-2013 Oracle and/or its affiliates. All rights reserved.

    The contents of this file are subject to the terms of either the GNU
    General Public License Version 2 only ("GPL") or the Common Development
    and Distribution License("CDDL") (collectively, the "License").  You
    may not use this file except in compliance with the License.  You can
    obtain a copy of the License at
    https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html
    or packager/legal/LICENSE.txt.  See the License for the specific
    language governing permissions and limitations under the License.

    When distributing the software, include this License Header Notice in each
    file and include the License file at packager/legal/LICENSE.txt.

    GPL Classpath Exception:
    Oracle designates this particular file as subject to the "Classpath"
    exception as provided by Oracle in the GPL Version 2 section of the License
    file that accompanied this code.

    Modifications:
    If applicable, add the following below the License Header, with the fields
    enclosed by brackets [] replaced by your own identifying information:
    "Portions Copyright [year] [name of copyright owner]"

    Contributor(s):
    If you wish your version of this file to be governed by only the CDDL or
    only the GPL Version 2, indicate your decision by adding "[Contributor]
    elects to include this software in this distribution under the [CDDL or GPL
    Version 2] license."  If you don't indicate a single choice of license, a
    recipient has the option to distribute your version of this file under
    either the CDDL, the GPL Version 2 or to extend the choice of license to
    its licensees as provided above.  However, if you add GPL Version 2 code
    and therefore, elected the GPL Version 2 license, then the option applies
    only if the new code is made subject to such option by the copyright
    holder.

-->
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
<h:head>
</h:head>

     <script type="text/javascript">
      var onload_cb = function() {}
      var statusUpdate = function statusUpdate(data) {
         var statusArea = document.getElementById("statusArea");
         var text = statusArea.value;
         text = text + "Name: "+data.source.id;
         if (data.type === "event") {
             text = text +" Event: "+data.status+" ";
         }
         statusArea.value = text;
      }
    </script>

    <h:form id="myform" enctype="multipart/form-data" prependId="false">
        <p><h:inputFile id="file" value="#{fileUploadBean.uploadedFile}"> 
           <f:validator validatorId="FileValidator" />
       </h:inputFile>
        </p>
       <br/>
       
       <h:commandButton id="button" value="submit">
          <f:ajax execute="@all" render="@all" onevent="statusUpdate"/>
       </h:commandButton>
       
       #{fileUploadBean.fileText}
       
       <p><h:messages id="messages" /></p>
    </h:form>

    <p>
      <h3> Status:</h3>
      <textarea id="statusArea" cols="40" rows="10" readonly="readonly" />
    </p>

    <p>
      <h3>Testing This Page</h3>
      <ul>
      <li>Press the <i>Browse...</i> button</li>
      <li>Navigate to <i>javaee7/jsf/fileupload</i> directory if not already there.</li>
      <li>Select <i>inputFileSuccess.txt</i></li>
      <li>Press the <i>Submit</i> button.</li>
      <li>You should see the text: <i>This file contains the string JSR-344 and will be successfully set into the model. </i></li>
      </ul> 
    </p>
    <p>
      <ul>
      <li>Press the <i>Browse...</i> button</li>
      <li>Navigate to <i>basic</i> directory if not already there.</li>
      <li>Select <i>inputFileFailure.txt</i></li>
      <li>Press the <i>Submit</i> button.</li>
      <li>You should see the text: <i>Invalid file. File must contain special string .</i></li>
      </ul> 
    </p>
    <p>
    In both cases, you should end up with a message in the Status box: <i>Name: button Event: success</i><br/>
    This inicates the Ajax request has gone through the JSF Ajax lifecycle and is receiving the standard<br/>
    Ajax lifecycle events.
    </p>


</html>